### ISSUE TITLE
Unwanted textView scroll after attributed string update

### ISSUE THREAD

**Issue by bardonadam** [niw/KeyboardGuide#2]
I've added constraints to a text view as it is in the guid:
```
textView.translatesAutoresizingMaskIntoConstraints = false
textView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor).isActive = true
textView.leadingAnchor.constraint(equalTo: view.leadingAnchor).isActive = true
textView.trailingAnchor.constraint(equalTo: view.trailingAnchor).isActive = true
textView.bottomAnchor.constraint(equalTo: view.keyboardSafeArea.layoutGuide.bottomAnchor).isActive = true
```

And it works fine, except for one thing. The textView has an editable attributed string, like a rich text editor, with a toolbar as a keyboard's accessory view. When I tap on a button in the toolbar to do some action, which updates the attributed string's attributes, the textView will scroll to the bottom.

When I changed the bottom constraint to `view.safeAreaLayoutGuide.bottomAnchor`, the unwanted scroll disappeared. Any ideas what might be causing it, and how to prevent this?

Regardless, this is a great library, so thank you for sharing it!

**Comment by niw** [comment]
Well, without actual code or example project that can reproduce the problem, I can’t say what is the exact issue but... I think `UITextView` will scroll to the current `selectedRange` position when its `attributedText` is modified anyways, with or without constraints to the keyboard safe area.

Probably you don’t see the scroll because the text length is longer than the height without area covered by keyboard but shorter than entire view height. In that case the scroll is happening only when the text view’s height is adjusted by the keyboard safe area layout guide when it is appeared.

**Comment by bardonadam** [comment]
> I think UITextView will scroll to the current selectedRange position when its attributedText is modified anyways

Thing is it scrolls outside of the selectedRange. I have selected some word, modify the attributedText, scroll happens and that selected word/cursor position is hidden.

I was thinking what's the best/easiest way to provide my code, here's what I did - I've opened the repository's example and made following changes to the `SwiftViewController.swift` file:

Added UITextView extension:

```
extension UITextView {
    func updateTextAlignment(with textAlignment: NSTextAlignment) {
        guard let font = font, let text = text as NSString? else { return }
        
        let paragraphRange = text.paragraphRange(for: selectedRange)
        let paragraphStyle = NSMutableParagraphStyle()
        paragraphStyle.alignment = textAlignment
        
        // modify selected text, otherwise write new text/move current paragraph to center
        if selectedRange.length > 0 {
            var currentAttributes = [NSRange: [NSAttributedString.Key: Any]]()
            
            // Store current attributes
            attributedText.enumerateAttributes(in: selectedRange, options: .reverse, using: { attribute, range, _ in
                currentAttributes[range] = attribute
            })
            
            // Update text alignment(this also removes all the attributes)
            modifyTextInTextView(with: [.paragraphStyle: paragraphStyle], range: paragraphRange)
            
            // Update aligned text with stored attributes
            for (key, value) in currentAttributes {
                modifyTextInTextView(with: value, range: key)
            }
        }
        else {
            // Align text to be written
            let attributes: [NSAttributedString.Key : Any] = [.font: font, .paragraphStyle: paragraphStyle]
            typingAttributes = attributes
            
            // Align current paragrah
            modifyTextInTextView(with: [.paragraphStyle: paragraphStyle], range: paragraphRange)
        }
    }
    
    private func modifyTextInTextView(with attributes: [NSAttributedString.Key : Any], range: NSRange) {
        guard let startPosition = position(from: beginningOfDocument, offset: selectedRange.lowerBound),
              let endPosition = position(from: startPosition, offset: selectedRange.length) else { return }
        
        let modifiedAttributedText = NSMutableAttributedString(attributedString: attributedText)
        modifiedAttributedText.addAttributes(attributes, range: range)
        
        attributedText = modifiedAttributedText
        
        // Preserve the cursor & selection
        selectedTextRange = textRange(from: startPosition, to: endPosition)
    }
}
```


Changed the behaviour of `useContentInsetsSwitchDidChange`:
```
@objc private func useContentInsetsSwitchDidChange(_ sender: AnyObject) {
    let alignments: [NSTextAlignment] = [.left, .center, .right, .justified]
        
    textView?.updateTextAlignment(with: alignments.randomElement()!)
}
```

Now just click inside of some paragraph and toggle the `Use text view content insets` switch to trigger the update of textView's attributed string. The scroll will happen.

**Comment by niw** [comment]
Thank you for the example, let me check this out soon.

**Comment by niw** [comment]
So, this is unrelated to KeyboardGuide library or its example application implementation. In fact, I can reproduce this behavior without KeyboardGuide.

This is because `UITextView`’s `setAttributeText:` is forcibly change `selectedRange` to the end of text and triggers scroll on scroll view to try to show that area, which is `UITextView`’s specification.
You can see this behavior by implementing own `UITextView` subclass and override `setSelectedRange:` and `setContentOffset:`.

For your application use case however, I think you want to apply attributes without having such side effects. To do so, you need to modify `textStorage` directly without using `UITextView`’s properties and manage the change properly.
This is too much simple implementation though, try next one instead.
```
private func modifyTextInTextView(with attributes: [NSAttributedString.Key : Any], range: NSRange) {
    textStorage.beginEditing()
    textStorage.addAttributes(attributes, range: range)
    textStorage.endEditing()
}
```
This storage change doesn’t impact any user interface level behaviors such as `selectedRange` or scroll position.

**Comment by bardonadam** [comment]
It works! You're a lifesaver. Thank you so much for your help!
