### ISSUE TITLE
Would you publish to CocoaPods for using as dependency in podspec?

### ISSUE THREAD

**Issue by muukii** [niw/KeyboardGuide#3]
Hello, thank you for the great library.

Could you publish this library to CocoaPods? Because I'm thinking about creating a library that uses KeyboardGuide and publishing.
but it can't describe dependency since KeyboardGuide is not in CocoaPod specs.

If you have no time and you don't mind, I can publish it instead of you with the following podspec.
or is it better to do this on my own fork?

```
Pod::Spec.new do |spec|
  spec.name = "KeyboardGuide"
  spec.version = "0.2.0" # Find the current version from the version tags.
  spec.authors = "niw"
  spec.summary = "KeyboardGuide"
  spec.homepage = "https://github.com/niw/KeyboardGuide"
  spec.platform = :ios, "11.0"
  spec.source = {
    :git => "https://github.com/niw/KeyboardGuide.git", :tag => "#{spec.version}"
  }
  spec.source_files  = "Sources/KeyboardGuide/*.swift"
end
```

**Comment by niw** [comment]
Hi, @muukii! Thank you for asking about CocoaPods. I wonder if you’re planing to use this library as a dependency of your library project which need to have a dependency description in CocoaPods which can't be described as local git source dependency?

I haven’t think about such use case (only for direct dependency from the application,) and if so, likely I want to research a little bit about CocoaPods again and if it’s absolutely needed, I don’t too much mind to publish this library to CocoaPods.

To be honest, though, ideally everyone can simply use Swift Package Manager as a dependency tool... since it’s I think de-facto for Apple platform development nowadays.

**Comment by muukii** [comment]
@niw 
Thank you for your reply.

Yes, I want to create a package for CocoaPods that depends on KeyboardGuide.
The podspec to publish can only have dependencies that are published on pods as well.
And I could relate with publishing to CocoaPods making us tired.

But for several reasons, I need to continue using CocoaPods in my project.
I think also it would be getting better and SwiftPM would be a standard tool to manage packages.

**Comment by niw** [comment]
It is published now. https://cocoapods.org/pods/KeyboardGuide

**Comment by muukii** [comment]
@niw 
oops, sorry for late!
Thank you so much for publishing this library, now I can create a package built on top of KeyboardGuide.
